# Generated by axklim/flyspace's release workflow from
# packaging/flyspace.rb.tmpl. Edit it there — the next release overwrites
# this file.
class Flyspace < Formula
  desc "macOS workspace switcher for people who do not tile"
  homepage "https://github.com/axklim/flyspace"
  url "https://github.com/axklim/flyspace/archive/refs/tags/v0.1.1.tar.gz"
  sha256 "691c4b914e4f3118b704a5fec607d6dc79bb6b4fe6f56694a3d434b1ee110fa4"
  license "MIT"
  head "https://github.com/axklim/flyspace.git", branch: "main"

  # Package.swift pins the same floor; macOS 14 is where the AX and display
  # APIs the daemon uses behave as the design assumes.
  depends_on macos: :sonoma

  # Built here rather than shipped prebuilt, and that is the whole point:
  # macOS ties the Accessibility grant to the code signature, so only a build
  # on this machine can reach the user's "flyspace-dev" certificate and
  # produce a signature the grant survives (see caveats). The Command Line
  # Tools Homebrew already requires carry the Swift toolchain, so a source
  # build costs a dependency on nothing.
  def install
    # SwiftPM wraps manifest compilation in its own sandbox-exec, and nesting
    # that inside Homebrew's fails with "Invalid manifest".
    ENV["SWIFT_FLAGS"] = "--disable-sandbox"
    system "scripts/build.sh"

    prefix.install "build/Flyspace.app"
    bin.install "build/bin/flyspace"
    # Not in bin: it is a one-off the caveats point at, not a command.
    libexec.install "scripts/make-cert.sh"
  end

  # The bundle's own executable, not `flyspace daemon`: launchd should own the
  # daemon process directly, and it is the bundle that carries the identity
  # the Accessibility grant is attached to.
  service do
    run opt_prefix/"Flyspace.app/Contents/MacOS/flyspace-daemon"
    keep_alive true
    run_type :immediate
    log_path var/"log/flyspace.log"
    error_log_path var/"log/flyspace.log"
  end

  def caveats
    <<~EOS
      Grant Accessibility to
        #{opt_prefix}/Flyspace.app
      in System Settings > Privacy & Security > Accessibility. Without it the
      daemon idles: no hotkey fires and no window moves.

      Then:
        flyspace config default > ~/.config/flyspace/config.toml   # edit the bindings
        brew services start flyspace                               # or: flyspace daemon

      macOS ties that grant to the code signature. This formula signs with the
      self-signed "flyspace-dev" certificate when the keychain has one and
      ad-hoc when it does not — and an ad-hoc signature is a fresh identity
      every build, so the next upgrade silently drops the grant. To make it
      stick, once:

        #{opt_libexec}/make-cert.sh
        brew reinstall flyspace
        tccutil reset Accessibility design.flyspace

      and approve the prompt again. Every upgrade after that is signed with the
      same certificate and the grant survives it.

      If the daemon ever dies with windows parked off-screen, `flyspace rescue`
      pulls them back — it works without the daemon.
    EOS
  end

  test do
    # The check nothing else can make: that the tarball at `url` really is the
    # tag this formula names. The binary's version comes from the tag stamped
    # into the tarball by `git archive`; this one comes from the URL. They can
    # only disagree if the formula points at something other than it claims.
    assert_equal "flyspace #{version}", shell_output("#{bin}/flyspace --version").strip

    assert_match "flyspace <command>", shell_output("#{bin}/flyspace --help")

    # Entirely client-side, so it needs neither a daemon nor the grant.
    assert_match "[keys]", shell_output("#{bin}/flyspace config default")

    # The other half of the install: bin/flyspace alone is a client with
    # nothing to talk to.
    assert_path_exists prefix/"Flyspace.app/Contents/MacOS/flyspace-daemon"
  end
end
