# Generated by axklim/flytab's release workflow from
# packaging/flytab.rb.tmpl. Edit it there — the next release overwrites
# this file.
class Flytab < Formula
  desc "Cmd-Tab switcher that never causes an AeroSpace workspace jump"
  homepage "https://github.com/axklim/flytab"
  url "https://github.com/axklim/flytab/archive/refs/tags/v0.2.0.tar.gz"
  sha256 "ecf466ad2e85f57cf6a0cf29f8f94a373f08e21ef0b6bffb2c450435d473849e"
  license "MIT"
  head "https://github.com/axklim/flytab.git", branch: "main"

  depends_on :macos

  # Built here rather than shipped prebuilt, and that is the whole point:
  # macOS ties the Accessibility grant to the code signature, so only a build
  # on this machine can reach the user's "flytab-dev" certificate and produce a
  # signature the grant survives (see caveats). The Command Line Tools Homebrew
  # already requires carry the Swift compiler, so a source build costs a
  # dependency on nothing.
  def install
    system "scripts/build.sh"

    prefix.install "build/Flytab.app"
    # Not in bin: it is a one-off the caveats point at, not a command.
    libexec.install "scripts/make-cert.sh"
  end

  service do
    run opt_prefix/"Flytab.app/Contents/MacOS/flytab"
    keep_alive true
    run_type :immediate
    log_path var/"log/flytab.log"
    error_log_path var/"log/flytab.log"
  end

  def caveats
    <<~EOS
      flytab drives AeroSpace 0.21.0 or newer:
        brew install --cask nikitabobko/tap/aerospace

      Start it with:
        brew services start flytab

      Then grant Accessibility to
        #{opt_prefix}/Flytab.app
      in System Settings > Privacy & Security > Accessibility. Without it no
      event tap is installed and Cmd-Tab keeps its native behaviour. flytab
      polls for the grant, so there is nothing to restart once you approve it.

      macOS ties that grant to the code signature. This formula signs with the
      self-signed "flytab-dev" certificate when the keychain has one and ad-hoc
      when it does not — and an ad-hoc signature is a fresh identity every
      build, so the next upgrade silently drops the grant. To make it stick,
      once:

        #{opt_libexec}/make-cert.sh
        brew reinstall flytab
        tccutil reset Accessibility com.axklim.flytab

      and approve the prompt again. Every upgrade after that is signed with the
      same certificate and the grant survives it.
    EOS
  end

  test do
    # The check nothing else can make: that the tarball at `url` really is the
    # tag this formula names. The binary's version comes from the tag stamped
    # into the tarball by `git archive`; this one comes from the URL. They can
    # only disagree if the formula points at something other than it claims.
    assert_equal "flytab #{version}",
                 shell_output("#{prefix}/Flytab.app/Contents/MacOS/flytab --version").strip
  end
end
