# Generated by axklim/workenv's release workflow from
# packaging/workenv.rb.tmpl. Edit it there — the next release overwrites
# this file.
class Workenv < Formula
  desc "Open a task's git worktree, tmux session and terminal in one command"
  homepage "https://github.com/axklim/workenv"
  # No explicit version, and the asset names below are why it is safe to
  # leave out. Homebrew scans the version from the URL and `brew audit`
  # rejects stating it as well; but an `…-arm64.tar.gz` suffix gave the scan
  # a bare "64" to find, which is how a v0.1.1 formula shipped reporting its
  # version as "64". The platform labels carry no digits, so the version is
  # the only number in the name and the scan cannot pick the wrong one.
  license "MIT"

  depends_on "gh"
  depends_on "tmux"
  uses_from_macos "git"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/axklim/workenv/releases/download/v0.1.2/workenv-0.1.2-macos-arm.tar.gz"
      sha256 "5ef7ebef28bf2520dd8123e6eae5667a4a2f58d3193ebfd6645ae3bffcd15456"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/axklim/workenv/releases/download/v0.1.2/workenv-0.1.2-linux-intel.tar.gz"
      sha256 "e13b907ec273408e4a3c5ec579d69ee9e652f1cc96820ef94cd8f82abdf3155e"
    end
    on_arm do
      url "https://github.com/axklim/workenv/releases/download/v0.1.2/workenv-0.1.2-linux-arm.tar.gz"
      sha256 "b15ca98a04e0fcf9ed828dfeb26d6e76d6b05ec8b491657ff6e8a5326fbeaf66"
    end
  end

  def install
    bin.install "we"
  end

  def caveats
    <<~EOS
      we opens its terminal with Ghostty, which a formula cannot depend on:

        brew install --cask ghostty

      It also runs `claude` in the first tmux window. Claude Code is not a
      Homebrew package — install it separately, or point claude_cmd at
      something else in ~/.config/workenv/config.toml.

      Neither is needed for `we open --no-terminal`, nor on a remote host
      reached with `we --host`.
    EOS
  end

  test do
    # The check nothing else can make: a formula bumped to a version whose
    # asset was built from something else.
    assert_equal version.to_s, shell_output("#{bin}/we --version").strip

    # `we` with no arguments exits non-zero, so the usage check uses `help`.
    assert_match "we open", shell_output("#{bin}/we help")
  end
end
