# Generated by axklim/workenv's release workflow from
# packaging/workenv.rb.tmpl. Edit it there — the next release overwrites
# this file.
class Workenv < Formula
  desc "Open a task's git worktree, tmux session and terminal in one command"
  homepage "https://github.com/axklim/workenv"
  # No explicit version, and the asset names below are why it is safe to
  # leave out. Homebrew scans the version from the URL and `brew audit`
  # rejects stating it as well; but an `…-arm64.tar.gz` suffix gave the scan
  # a bare "64" to find, which is how a v0.1.1 formula shipped reporting its
  # version as "64". The platform labels carry no digits, so the version is
  # the only number in the name and the scan cannot pick the wrong one.
  license "MIT"

  depends_on "gh"
  depends_on "tmux"
  uses_from_macos "git"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/axklim/workenv/releases/download/v0.2.3/workenv-0.2.3-macos-arm.tar.gz"
      sha256 "a7e7aa61722e551a1c0d2c38d561018d911a9b7616373731df1a8cd8474f604c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/axklim/workenv/releases/download/v0.2.3/workenv-0.2.3-linux-intel.tar.gz"
      sha256 "8e1519b12f7582fc4409bba8ed27c072f5fd94eec50317808cf29703bf7d6a07"
    end
    on_arm do
      url "https://github.com/axklim/workenv/releases/download/v0.2.3/workenv-0.2.3-linux-arm.tar.gz"
      sha256 "8e123b534fb0cad6e265c76542dfa356b2ca8e4bef85d4528ebf656687f8407c"
    end
  end

  def install
    bin.install "we"
    pkgshare.install "skills"
  end

  def caveats
    <<~EOS
      we opens its terminal with Ghostty, which a formula cannot depend on:

        brew install --cask ghostty

      It also runs `claude` in the first tmux window. Claude Code is not a
      Homebrew package — install it separately, or point claude_cmd at
      something else in ~/.config/workenv/config.toml.

      Neither is needed for `we open --no-terminal`, nor on a remote host
      reached with `we --host`.

      The Claude Code skill that teaches a session to drive `we` ships here:

        #{pkgshare}/skills/we

      Link it into ~/.claude/skills/we (or let your dotfiles do it) so the
      skill always matches the installed version.
    EOS
  end

  test do
    # The check nothing else can make: a formula bumped to a version whose
    # asset was built from something else.
    assert_equal version.to_s, shell_output("#{bin}/we --version").strip

    # `we` with no arguments exits non-zero, so the usage check uses `help`.
    assert_match "we open", shell_output("#{bin}/we help")
    assert_path_exists pkgshare/"skills/we/SKILL.md"
  end
end
