# Generated by axklim/workenv's release workflow from
# packaging/workenv.rb.tmpl. Edit it there — the next release overwrites
# this file.
class Workenv < Formula
  desc "Open a task's git worktree, tmux session and terminal in one command"
  homepage "https://github.com/axklim/workenv"
  # No explicit version, and the asset names below are why it is safe to
  # leave out. Homebrew scans the version from the URL and `brew audit`
  # rejects stating it as well; but an `…-arm64.tar.gz` suffix gave the scan
  # a bare "64" to find, which is how a v0.1.1 formula shipped reporting its
  # version as "64". The platform labels carry no digits, so the version is
  # the only number in the name and the scan cannot pick the wrong one.
  license "MIT"

  depends_on "gh"
  depends_on "tmux"
  uses_from_macos "git"

  on_macos do
    depends_on arch: :arm64

    on_arm do
      url "https://github.com/axklim/workenv/releases/download/v0.2.2/workenv-0.2.2-macos-arm.tar.gz"
      sha256 "ba736b3f1ae1886b395c97ed1755fd1968c0b3fc01b7fc2316132d3f680f97d1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/axklim/workenv/releases/download/v0.2.2/workenv-0.2.2-linux-intel.tar.gz"
      sha256 "152e8ab6292f20f51c6e758fb41634536e2c9ec25d426ebe0883a6378ced5c61"
    end
    on_arm do
      url "https://github.com/axklim/workenv/releases/download/v0.2.2/workenv-0.2.2-linux-arm.tar.gz"
      sha256 "caa2091e1f1d9674849ccc836debad5d2148b96ab2556b3bfec8fcba61198896"
    end
  end

  def install
    bin.install "we"
    pkgshare.install "skills"
  end

  def caveats
    <<~EOS
      we opens its terminal with Ghostty, which a formula cannot depend on:

        brew install --cask ghostty

      It also runs `claude` in the first tmux window. Claude Code is not a
      Homebrew package — install it separately, or point claude_cmd at
      something else in ~/.config/workenv/config.toml.

      Neither is needed for `we open --no-terminal`, nor on a remote host
      reached with `we --host`.

      The Claude Code skill that teaches a session to drive `we` ships here:

        #{pkgshare}/skills/we

      Link it into ~/.claude/skills/we (or let your dotfiles do it) so the
      skill always matches the installed version.
    EOS
  end

  test do
    # The check nothing else can make: a formula bumped to a version whose
    # asset was built from something else.
    assert_equal version.to_s, shell_output("#{bin}/we --version").strip

    # `we` with no arguments exits non-zero, so the usage check uses `help`.
    assert_match "we open", shell_output("#{bin}/we help")
    assert_path_exists pkgshare/"skills/we/SKILL.md"
  end
end
